language: node_js
install: false
cache:
  directories:
  - node_modules
  - packages/*/node_modules
  - packages/*/dist
  - packages/*/build
dist: trusty
sudo: required
install: true
jobs:
  include:
    - stage: "Build"
      script:
        - npm install    || travis_terminate 1;
        - npm run lint    || travis_terminate 1;
        - npm run build   || travis_terminate 1;
    - stage: "Tests"
      name: "Unit Tests"
      script: npm run test || travis_terminate 1;
    - script: npm run test:e2e || travis_terminate 1;
      name: "E2E Tests"
notifications:
  email:
    recipients:
    - guyso@wix.com
